package space.createyourhumanity.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GrantSettingsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrantSettingsAllPropertiesEquals(GrantSettings expected, GrantSettings actual) {
        assertGrantSettingsAutoGeneratedPropertiesEquals(expected, actual);
        assertGrantSettingsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrantSettingsAllUpdatablePropertiesEquals(GrantSettings expected, GrantSettings actual) {
        assertGrantSettingsUpdatableFieldsEquals(expected, actual);
        assertGrantSettingsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrantSettingsAutoGeneratedPropertiesEquals(GrantSettings expected, GrantSettings actual) {
        assertThat(expected)
            .as("Verify GrantSettings auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrantSettingsUpdatableFieldsEquals(GrantSettings expected, GrantSettings actual) {
        assertThat(expected)
            .as("Verify GrantSettings relevant properties")
            .satisfies(e -> assertThat(e.getGrantMap()).as("check grantMap").isEqualTo(actual.getGrantMap()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrantSettingsUpdatableRelationshipsEquals(GrantSettings expected, GrantSettings actual) {}
}
