package space.createyourhumanity.app.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static space.createyourhumanity.app.domain.AssertUtils.zonedDataTimeSameInstant;

public class UserMindmapAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserMindmapAllPropertiesEquals(UserMindmap expected, UserMindmap actual) {
        assertUserMindmapAutoGeneratedPropertiesEquals(expected, actual);
        assertUserMindmapAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserMindmapAllUpdatablePropertiesEquals(UserMindmap expected, UserMindmap actual) {
        assertUserMindmapUpdatableFieldsEquals(expected, actual);
        assertUserMindmapUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserMindmapAutoGeneratedPropertiesEquals(UserMindmap expected, UserMindmap actual) {
        assertThat(expected)
            .as("Verify UserMindmap auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserMindmapUpdatableFieldsEquals(UserMindmap expected, UserMindmap actual) {
        assertThat(expected)
            .as("Verify UserMindmap relevant properties")
            .satisfies(e -> assertThat(e.getText()).as("check text").isEqualTo(actual.getText()))
            .satisfies(
                e ->
                    assertThat(e.getModified())
                        .as("check modified")
                        .usingComparator(zonedDataTimeSameInstant)
                        .isEqualTo(actual.getModified())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserMindmapUpdatableRelationshipsEquals(UserMindmap expected, UserMindmap actual) {}
}
